### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xpascal#1]
In order to launch we should:

- [ ] Turn on Travis CI for the track (kytrinyx)
- [ ] Add Pascal as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/tracks) (kytrinyx)
- [ ] Define `test_pattern` in `config.json` (see below)
- [ ] Implement at least 10 problems (See the [guide](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track))
- [ ] Write documentation (see below)
- [ ] Find a person or (ideally) a handful of people willing to check exercism regularly (daily?) to review solutions
- [ ] Add track implementors and other designated code reviewers as mentors to the track. This gives you access to all the solutions in Pascal whether or not you've submitted the problem to the site. The first track mentor needs to be added manually by kytrinyx, but after that there's a section in the account where existing track mentors can invite new ones.
- [ ] Add a language icon or logo (see below) + attribution (in README)
- [ ] Read the maintainer docs:
      - [Maintaining a Track](https://github.com/exercism/exercism.io/blob/master/docs/maintaining-a-track.md)
      - [Reviewing a Pull Request](https://github.com/exercism/exercism.io/blob/master/docs/reviewing-a-pull-request.md)
- [ ] Toggle `"active"` to `true` in `config.json`
- [ ] Mention it in the next "Behind the Scenes" newsletter (kytrinyx)

## Test Pattern

The `config.json` has a key, `"test_pattern"` which should be a string that can be compiled as a regex matching the pattern for a test file in this track. If the test files contain the word "test" (case insensitive) then the `"test_pattern"` key can be deleted.

## Documentation

The documentation lives in the `docs/` directory here in this repository, and gets served to the site via the x-api. It should contain at minimim:

- `INSTALLATION.md` - about how to get the language set up locally.
- `TESTS.md` - about how to run the tests for the exercises.

Some nice to haves:

- `ABOUT.md` - a short, friendly blurb about the language. What types of problems does it solve really well? What is it typically used for?
- `LEARNING.md` - a few notes about where people might want to go to learn the language from scratch.
- `RESOURCES.md` - references and other useful resources.

## Logo/Icon

We try to create a language icon that has the exercism colors, and is recognizably similar to the language icon. Sometimes this isn't possible due to copyright issues. See http://exercism.io/languages for all the existing icons.

We're in the process of moving each individual language track icon into the specific language track repository. Putting all the language-specific stuff together makes it easier to manage. In the meanwhile, we need to have everything in two places.

If image assets are not your strong suit, just find a reasonable image to start from, along with the information about the licensing, and we'll figure out the colorization thing (I've written some scripts to help me do this part).

Some icons are the official language logo (tweaked). Where a language doesn't seem to have an official logo, or where the official logo has copyright issues, we just make something up.

**exercism.io**

The logo should be named `pascal.png` and live in `/public/img/tracks/` in the exercism/exercism.io repository.
https://github.com/exercism/exercism.io/tree/master/public/img/tracks

Attribution goes in https://github.com/exercism/exercism.io/blob/master/ATTRIBUTION.md

**xpascal**

The logo should be named `icon.png` and live under `img/` in this repository. If you know how, go ahead and make an SVG as well.

Attribution goes in the README.md file.

## Successful Launches

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The code reviews do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore aspects of the language. Referencing existing blog posts and style guides seems to work well, when making specific recommendations.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md
